latent_dim: 50
num_chars: 73
num_style_labels: 0

step: 1 # Reduce size of dataset by this factor
first_n_fonts: 0 # Prune dataset

########     4      8     16    32    64    128   256   512   1024
filters:    [512,   256,  256,  128,  128,  64,   64,   32,   16] # Filters per added layer (in discriminator und generator)
batch_size: [64,    32,   32,   16,   8,    4,    4,    2,    1] # Batches per stage
epochs:     [1,     1,    1,    1,    2,    5,    5,    5,    5] # Epochs per stage
discriminator_steps: 3

font_dir: 'C:/Users/Schnee/Datasets/Fonts01CleanUp/' # Local
#font_dir: '../Datasets/Fonts01CleanUp/' # Remote

save_model: False # Saves model weights(discriminator/generator) + complete generator model for inference